In [1]:
import pandas as pd
import numpy as np

In [2]:
books= pd.read_csv("Books.csv")
ratings= pd.read_csv("Ratings.csv")
users=pd.read_csv("Users.csv")

C:\Users\Yashpal\AppData\Local\Temp\ipykernel_15736\347764371.py:1: DtypeWarning: Columns (3) have mixed types. Specify dtype option on import or set low_memory=False.
  books= pd.read_csv("Books.csv")

In [3]:
books.head(1)

,ISBN,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,0195153448,Classical Mythology,Mark P. O. Morford,2002,Oxford University Press,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...,http://images.amazon.com/images/P/0195153448.0...

In [4]:
ratings.head(1)

   User-ID        ISBN  Book-Rating
0   276725  034545104X            0

In [7]:
users.head(1)

   User-ID            Location  Age
0        1  nyc, new york, usa  NaN

In [8]:
print(books.shape)
print(users.shape)
print(ratings.shape)

(271360, 8)
(278858, 3)
(1149780, 3)

In [9]:
books.isnull().sum()

ISBN                   0
Book-Title             0
Book-Author            2
Year-Of-Publication    0
Publisher              2
Image-URL-S            0
Image-URL-M            0
Image-URL-L            3
dtype: int64

In [13]:
users.isnull().sum()

User-ID          0
Location         0
Age         110762
dtype: int64

In [14]:
ratings.isnull().sum()

User-ID        0
ISBN           0
Book-Rating    0
dtype: int64

In [15]:
books.duplicated().sum()

0

In [16]:
users.duplicated().sum()

0

In [17]:
ratings.duplicated().sum()

0

# Popularity Based Recommender System

In [19]:
ratings.merge(books, on='ISBN')

,User-ID,ISBN,Book-Rating,Book-Title,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
0,276725,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
1,2313,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
2,6543,034545104X,0,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
3,8680,034545104X,5,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
4,10314,034545104X,9,Flesh Tones: A Novel,M. J. Rose,2002,Ballantine Books,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...,http://images.amazon.com/images/P/034545104X.0...
...,...,...,...,...,...,...,...,...,...,...
1031131,276688,0517145553,0,Mostly Harmless,Douglas Adams,1995,Random House Value Pub,http://images.amazon.com/images/P/0517145553.0...,http://images.amazon.com/images/P/0517145553.0...,http://images.amazon.com/images/P/0517145553.0...
1031132,276688,1575660792,7,Gray Matter,Shirley Kennett,1996,Kensington Publishing Corporation,http://images.amazon.com/images/P/1575660792.0...,http://images.amazon.com/images/P/1575660792.0...,http://images.amazon.com/images/P/1575660792.0...
1031133,276690,0590907301,0,Triplet Trouble and the Class Trip (Triplet Tr...,Debbie Dadey,1997,Apple,http://images.amazon.com/images/P/0590907301.0...,http://images.amazon.com/images/P/0590907301.0...,http://images.amazon.com/images/P/0590907301.0...
1031134,276704,0679752714,0,A Desert of Pure Feeling (Vintage Contemporaries),Judith Freeman,1997,Vintage Books USA,http://images.amazon.com/images/P/0679752714.0...,http://images.amazon.com/images/P/0679752714.0...,http://images.amazon.com/images/P/0679752714.0...
1031135,276704,0806917695,5,Perplexing Lateral Thinking Puzzles: Scholasti...,Paul Sloane,1997,Sterling Publishing,http://images.amazon.com/images/P/0806917695.0...,http://images.amazon.com/images/P/0806917695.0...,http://images.amazon.com/images/P/0806917695.0...

In [21]:
ratings_with_name= ratings.merge(books, on="ISBN")

In [23]:
ratings_with_name.groupby("Book-Title").count()

,User-ID,ISBN,Book-Rating,Book-Author,Year-Of-Publication,Publisher,Image-URL-S,Image-URL-M,Image-URL-L
Book-Title,,,,,,,,,
"A Light in the Storm: The Civil War Diary of Amelia Martin, Fenwick Island, Delaware, 1861 (Dear America)",4,4,4,4,4,4,4,4,4
Always Have Popsicles,1,1,1,1,1,1,1,1,1
Apple Magic (The Collector's series),1,1,1,1,1,1,1,1,1
"Ask Lily (Young Women of Faith: Lily Series, Book 5)",1,1,1,1,1,1,1,1,1
Beyond IBM: Leadership Marketing and Finance for the 1990s,1,1,1,1,1,1,1,1,1
...,...,...,...,...,...,...,...,...,...
Ã?Â?lpiraten.,2,2,2,2,2,2,2,2,2
Ã?Â?rger mit Produkt X. Roman.,4,4,4,4,4,4,4,4,4
Ã?Â?sterlich leben.,1,1,1,1,1,1,1,1,1
Ã?Â?stlich der Berge.,3,3,3,3,3,3,3,3,3
Ã?Â?thique en toc,2,2,2,2,2,2,2,2,2

In [24]:
ratings_with_name.groupby("Book-Title").count() ['Book-Rating']

Book-Title
 A Light in the Storm: The Civil War Diary of Amelia Martin, Fenwick Island, Delaware, 1861 (Dear America)    4
 Always Have Popsicles                                                                                        1
 Apple Magic (The Collector's series)                                                                         1
 Ask Lily (Young Women of Faith: Lily Series, Book 5)                                                         1
 Beyond IBM: Leadership Marketing and Finance for the 1990s                                                   1
                                                                                                             ..
Ã?Â?lpiraten.                                                                                                 2
Ã?Â?rger mit Produkt X. Roman.                                                                                4
Ã?Â?sterlich leben.                                                                                           1
Ã?Â?stlich der Berge.                                                                                         3
Ã?Â?thique en toc                                                                                             2
Name: Book-Rating, Length: 241071, dtype: int64

In [26]:
ratings_with_name.groupby("Book-Title").count() ['Book-Rating'].reset_index()

                                               Book-Title  Book-Rating
0        A Light in the Storm: The Civil War Diary of ...            4
1                                   Always Have Popsicles            1
2                    Apple Magic (The Collector's series)            1
3        Ask Lily (Young Women of Faith: Lily Series, ...            1
4        Beyond IBM: Leadership Marketing and Finance ...            1
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.            2
241067                     Ã?Â?rger mit Produkt X. Roman.            4
241068                                Ã?Â?sterlich leben.            1
241069                              Ã?Â?stlich der Berge.            3
241070                                  Ã?Â?thique en toc            2

[241071 rows x 2 columns]

In [27]:
num_rating_df=ratings_with_name.groupby("Book-Title").count() ['Book-Rating'].reset_index()

In [28]:
num_rating_df.rename(columns={"Book-Rating":"num_ratings"},inplace=True)
num_rating_df

                                               Book-Title  num_ratings
0        A Light in the Storm: The Civil War Diary of ...            4
1                                   Always Have Popsicles            1
2                    Apple Magic (The Collector's series)            1
3        Ask Lily (Young Women of Faith: Lily Series, ...            1
4        Beyond IBM: Leadership Marketing and Finance ...            1
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.            2
241067                     Ã?Â?rger mit Produkt X. Roman.            4
241068                                Ã?Â?sterlich leben.            1
241069                              Ã?Â?stlich der Berge.            3
241070                                  Ã?Â?thique en toc            2

[241071 rows x 2 columns]

In [36]:
avg_ratings_pre= ratings_with_name.groupby("Book-Title")

In [44]:
ratings_with_name.dtypes

User-ID                 int64
ISBN                   object
Book-Rating             int64
Book-Title             object
Book-Author            object
Year-Of-Publication    object
Publisher              object
Image-URL-S            object
Image-URL-M            object
Image-URL-L            object
dtype: object

In [46]:
ratings_with_name2= ratings_with_name.groupby("Book-Title")

In [52]:
ratings_with_name2

ratings_with_name2.dtypes

In [54]:
avg_ratings= ratings_with_name2["Book-Rating"].mean()
avg_ratings

Book-Title
 A Light in the Storm: The Civil War Diary of Amelia Martin, Fenwick Island, Delaware, 1861 (Dear America)    2.250000
 Always Have Popsicles                                                                                        0.000000
 Apple Magic (The Collector's series)                                                                         0.000000
 Ask Lily (Young Women of Faith: Lily Series, Book 5)                                                         8.000000
 Beyond IBM: Leadership Marketing and Finance for the 1990s                                                   0.000000
                                                                                                                ...
Ã?Â?lpiraten.                                                                                                 0.000000
Ã?Â?rger mit Produkt X. Roman.                                                                                5.250000
Ã?Â?sterlich leben.                                                                                           7.000000
Ã?Â?stlich der Berge.                                                                                         2.666667
Ã?Â?thique en toc                                                                                             4.000000
Name: Book-Rating, Length: 241071, dtype: float64

In [57]:
avg_ratings= avg_ratings.reset_index()

In [58]:
avg_ratings

                                               Book-Title  Book-Rating
0        A Light in the Storm: The Civil War Diary of ...     2.250000
1                                   Always Have Popsicles     0.000000
2                    Apple Magic (The Collector's series)     0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...     8.000000
4        Beyond IBM: Leadership Marketing and Finance ...     0.000000
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.     0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.     5.250000
241068                                Ã?Â?sterlich leben.     7.000000
241069                              Ã?Â?stlich der Berge.     2.666667
241070                                  Ã?Â?thique en toc     4.000000

[241071 rows x 2 columns]

In [59]:
avg_ratings= avg_ratings.rename(columns={"Book-Rating":"avg_ratings"})

In [60]:
avg_ratings

                                               Book-Title  avg_ratings
0        A Light in the Storm: The Civil War Diary of ...     2.250000
1                                   Always Have Popsicles     0.000000
2                    Apple Magic (The Collector's series)     0.000000
3        Ask Lily (Young Women of Faith: Lily Series, ...     8.000000
4        Beyond IBM: Leadership Marketing and Finance ...     0.000000
...                                                   ...          ...
241066                                      Ã?Â?lpiraten.     0.000000
241067                     Ã?Â?rger mit Produkt X. Roman.     5.250000
241068                                Ã?Â?sterlich leben.     7.000000
241069                              Ã?Â?stlich der Berge.     2.666667
241070                                  Ã?Â?thique en toc     4.000000

[241071 rows x 2 columns]

In [61]:
num_rating_df.merge(avg_ratings, on="Book-Title")

,Book-Title,num_ratings,avg_ratings
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000
1,Always Have Popsicles,1,0.000000
2,Apple Magic (The Collector's series),1,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000
...,...,...,...
241066,Ã?Â?lpiraten.,2,0.000000
241067,Ã?Â?rger mit Produkt X. Roman.,4,5.250000
241068,Ã?Â?sterlich leben.,1,7.000000
241069,Ã?Â?stlich der Berge.,3,2.666667
241070,Ã?Â?thique en toc,2,4.000000

In [62]:
popularity_df= num_rating_df.merge(avg_ratings, on="Book-Title")
popularity_df

,Book-Title,num_ratings,avg_ratings
0,A Light in the Storm: The Civil War Diary of ...,4,2.250000
1,Always Have Popsicles,1,0.000000
2,Apple Magic (The Collector's series),1,0.000000
3,"Ask Lily (Young Women of Faith: Lily Series, ...",1,8.000000
4,Beyond IBM: Leadership Marketing and Finance ...,1,0.000000
...,...,...,...
241066,Ã?Â?lpiraten.,2,0.000000
241067,Ã?Â?rger mit Produkt X. Roman.,4,5.250000
241068,Ã?Â?sterlich leben.,1,7.000000
241069,Ã?Â?stlich der Berge.,3,2.666667
241070,Ã?Â?thique en toc,2,4.000000

In [83]:
popular_df=popularity_df[popularity_df["num_ratings"]>=220]

In [84]:
popular_df

,Book-Title,num_ratings,avg_ratings
764,1984,284,4.454225
818,1st to Die: A Novel,509,3.575639
1048,2nd Chance,356,3.269663
1760,A Bend in the Road,346,3.364162
2120,A Case of Need,236,2.423729
...,...,...,...
233851,White Oleander : A Novel (Oprah's Book Club),356,3.772472
234740,Wicked: The Life and Times of the Wicked Witch...,326,3.766871
234951,Wild Animus,2502,1.019584
236334,Wish You Well,234,3.012821
240860,"\O\"" Is for Outlaw""",269,2.988848

In [85]:
popular_df.sort_values("avg_ratings", inplace= True, ascending= False)

C:\Users\Yashpal\AppData\Local\Temp\ipykernel_15736\1538304010.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  popular_df.sort_values("avg_ratings", inplace= True, ascending= False)

In [86]:
popular_df

,Book-Title,num_ratings,avg_ratings
80434,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804
80422,Harry Potter and the Goblet of Fire (Book 4),387,5.824289
80441,Harry Potter and the Sorcerer's Stone (Book 1),278,5.737410
80426,Harry Potter and the Order of the Phoenix (Boo...,347,5.501441
60582,Ender's Game (Ender Wiggins Saga (Paperback)),249,5.409639
...,...,...,...
27600,Breathing Lessons,239,2.117155
94382,Isle of Dogs,288,2.000000
162153,Slow Waltz in Cedar Bend,248,1.895161
163913,Songs in Ordinary Time (Oprah's Book Club (Pap...,232,1.857759
234951,Wild Animus,2502,1.019584

In [89]:
popular_df= popular_df.head(50)

In [90]:
popular_df

,Book-Title,num_ratings,avg_ratings
80434,Harry Potter and the Prisoner of Azkaban (Book 3),428,5.852804
80422,Harry Potter and the Goblet of Fire (Book 4),387,5.824289
80441,Harry Potter and the Sorcerer's Stone (Book 1),278,5.737410
80426,Harry Potter and the Order of the Phoenix (Boo...,347,5.501441
60582,Ender's Game (Ender Wiggins Saga (Paperback)),249,5.409639
80414,Harry Potter and the Chamber of Secrets (Book 2),556,5.183453
191612,The Hobbit : The Enchanting Prelude to The Lor...,281,5.007117
187377,The Fellowship of the Ring (The Lord of the Ri...,368,4.948370
80445,Harry Potter and the Sorcerer's Stone (Harry P...,575,4.895652
211384,"The Two Towers (The Lord of the Rings, Part 2)",260,4.880769
219741,To Kill a Mockingbird,510,4.700000
183573,The Da Vinci Code,898,4.642539
187880,The Five People You Meet in Heaven,430,4.551163
180556,The Catcher in the Rye,449,4.545657
196326,The Lovely Bones: A Novel,1295,4.468726
764,1984,284,4.454225
144165,Prodigal Summer: A Novel,253,4.450593
128670,Neverwhere,265,4.449057
206502,The Secret Life of Bees,774,4.447028
168719,Stupid White Men ...and Other Sorry Excuses fo...,283,4.356890
223135,"Tuesdays with Morrie: An Old Man, a Young Man,...",493,4.354970
204387,The Red Tent (Bestselling Backlist),723,4.334716
27295,Brave New World,226,4.331858
191589,The Hitchhiker's Guide to the Galaxy,268,4.328358
129379,Nickel and Dimed: On (Not) Getting By in America,335,4.289552
14607,Animal Farm,233,4.274678
93381,Into the Wild,252,4.273810
63867,Fahrenheit 451,409,4.264059
74750,Girl with a Pearl Earring,526,4.218631
136145,Outlander,283,4.173145
209209,"The Subtle Knife (His Dark Materials, Book 2)",225,4.124444
181699,The Color of Water: A Black Man's Tribute to H...,223,4.107623
233370,Where the Heart Is (Oprah's Book Club (Paperba...,585,4.105983
156102,Seabiscuit: An American Legend,275,4.098182
107962,Life of Pi,664,4.088855
176845,The Bean Trees,389,4.087404
2281,"A Child Called \It\"": One Child's Courage to S...",265,4.086792
8434,ANGELA'S ASHES,279,4.075269
83432,High Fidelity,247,4.056680
76343,Good in Bed,490,4.055102
64931,Fast Food Nation: The Dark Side of the All-Ame...,321,4.037383
12700,American Gods,302,4.006623
161645,Skipping Christmas,322,4.006211
105777,Left Behind: A Novel of the Earth's Last Days ...,318,4.003145
189551,"The Golden Compass (His Dark Materials, Book 1)",336,4.000000
181679,The Color Purple,314,3.964968
160336,Silence of the Lambs,256,3.960938
8752,About a Boy,262,3.900763
158138,Seven Up (A Stephanie Plum Novel),278,3.888489
175097,The Alchemist: A Fable About Following Your Dream,266,3.875940

In [93]:
popular_df= popular_df.merge(books,on= "Book-Title").drop_duplicates("Book-Title")[["Book-Title","Book-Author","Year-Of-Publication","Publisher","num_ratings","avg_ratings","Image-URL-M"]]

In [96]:
popular_df= popular_df.reset_index()

In [97]:
popular_df

,index,Book-Title,Book-Author,Year-Of-Publication,Publisher,num_ratings,avg_ratings,Image-URL-M
0,0,Harry Potter and the Prisoner of Azkaban (Book 3),J. K. Rowling,1999,Scholastic,428,5.852804,http://images.amazon.com/images/P/0439136350.0...
1,3,Harry Potter and the Goblet of Fire (Book 4),J. K. Rowling,2000,Scholastic,387,5.824289,http://images.amazon.com/images/P/0439139597.0...
2,5,Harry Potter and the Sorcerer's Stone (Book 1),J. K. Rowling,1998,Scholastic,278,5.737410,http://images.amazon.com/images/P/0590353403.0...
3,9,Harry Potter and the Order of the Phoenix (Boo...,J. K. Rowling,2003,Scholastic,347,5.501441,http://images.amazon.com/images/P/043935806X.0...
4,13,Ender's Game (Ender Wiggins Saga (Paperback)),Orson Scott Card,1992,Tor Books,249,5.409639,http://images.amazon.com/images/P/0312853238.0...
5,17,Harry Potter and the Chamber of Secrets (Book 2),J. K. Rowling,2000,Scholastic,556,5.183453,http://images.amazon.com/images/P/0439064872.0...
6,20,The Hobbit : The Enchanting Prelude to The Lor...,J.R.R. TOLKIEN,1986,Del Rey,281,5.007117,http://images.amazon.com/images/P/0345339681.0...
7,21,The Fellowship of the Ring (The Lord of the Ri...,J.R.R. TOLKIEN,1986,Del Rey,368,4.948370,http://images.amazon.com/images/P/0345339703.0...
8,30,Harry Potter and the Sorcerer's Stone (Harry P...,J. K. Rowling,1999,Arthur A. Levine Books,575,4.895652,http://images.amazon.com/images/P/059035342X.0...
9,32,"The Two Towers (The Lord of the Rings, Part 2)",J.R.R. TOLKIEN,1986,Del Rey,260,4.880769,http://images.amazon.com/images/P/0345339711.0...
10,43,To Kill a Mockingbird,Harper Lee,1988,Little Brown &amp; Company,510,4.700000,http://images.amazon.com/images/P/0446310786.0...
11,51,The Da Vinci Code,Dan Brown,2003,Doubleday,898,4.642539,http://images.amazon.com/images/P/0385504209.0...
12,57,The Five People You Meet in Heaven,Mitch Albom,2003,Hyperion,430,4.551163,http://images.amazon.com/images/P/0786868716.0...
13,59,The Catcher in the Rye,J.D. Salinger,1991,"Little, Brown",449,4.545657,http://images.amazon.com/images/P/0316769487.0...
14,66,The Lovely Bones: A Novel,Alice Sebold,2002,"Little, Brown",1295,4.468726,http://images.amazon.com/images/P/0316666343.0...
15,67,1984,George Orwell,1990,Signet Book,284,4.454225,http://images.amazon.com/images/P/0451524934.0...
16,76,Prodigal Summer: A Novel,Barbara Kingsolver,2001,Perennial,253,4.450593,http://images.amazon.com/images/P/0060959037.0...
17,77,Neverwhere,Neil Gaiman,1998,Avon,265,4.449057,http://images.amazon.com/images/P/0380789019.0...
18,82,The Secret Life of Bees,Sue Monk Kidd,2003,Penguin Books,774,4.447028,http://images.amazon.com/images/P/0142001740.0...
19,88,Stupid White Men ...and Other Sorry Excuses fo...,Michael Moore,2002,Regan Books,283,4.356890,http://images.amazon.com/images/P/0060392452.0...
20,89,"Tuesdays with Morrie: An Old Man, a Young Man,...",MITCH ALBOM,1997,Doubleday,493,4.354970,http://images.amazon.com/images/P/0385484518.0...
21,92,The Red Tent (Bestselling Backlist),Anita Diamant,1998,Picador USA,723,4.334716,http://images.amazon.com/images/P/0312195516.0...
22,93,Brave New World,Aldous Huxley,1989,Harpercollins,226,4.331858,http://images.amazon.com/images/P/0060809833.0...
23,98,The Hitchhiker's Guide to the Galaxy,Douglas Adams,1982,Pocket,268,4.328358,http://images.amazon.com/images/P/0671461494.0...
24,107,Nickel and Dimed: On (Not) Getting By in America,Barbara Ehrenreich,2002,Owl Books,335,4.289552,http://images.amazon.com/images/P/0805063897.0...
25,109,Animal Farm,George Orwell,2004,Signet,233,4.274678,http://images.amazon.com/images/P/0451526341.0...
26,119,Into the Wild,Jon Krakauer,1997,Anchor,252,4.273810,http://images.amazon.com/images/P/0385486804.0...
27,122,Fahrenheit 451,Ray Bradbury,1994,Distribooks Inc,409,4.264059,http://images.amazon.com/images/P/3257208626.0...
28,135,Girl with a Pearl Earring,Tracy Chevalier,2001,Plume Books,526,4.218631,http://images.amazon.com/images/P/0452282152.0...
29,136,Outlander,DIANA GABALDON,1996,Dell,283,4.173145,http://images.amazon.com/images/P/0440222915.0...
30,142,"The Subtle Knife (His Dark Materials, Book 2)",PHILIP PULLMAN,2002,Knopf Books for Young Readers,225,4.124444,http://images.amazon.com/images/P/0375823468.0...
31,150,The Color of Water: A Black Man's Tribute to H...,James McBride,1997,Riverhead Books,223,4.107623,http://images.amazon.com/images/P/1573225789.0...
32,152,Where the Heart Is (Oprah's Book Club (Paperba...,Billie Letts,1998,Warner Books,585,4.105983,http://images.amazon.com/images/P/0446672211.0...
33,153,Seabiscuit: An American Legend,LAURA HILLENBRAND,2002,Ballantine Books,275,4.098182,http://images.amazon.com/images/P/0449005615.0...
34,155,Life of Pi,Yann Martel,2002,Harcourt,664,4.088855,http://images.amazon.com/images/P/0151008116.0...
35,159,The Bean Trees,Barbara Kingsolver,1989,Perennial,389,4.087404,http://images.amazon.com/images/P/0060915544.0...
36,162,"A Child Called \It\"": One Child's Courage to S...",Dave Pelzer,1995,Health Communications,265,4.086792,http://images.amazon.com/images/P/1558743669.0...
37,164,ANGELA'S ASHES,Frank McCourt,1996,Scribner,279,4.075269,http://images.amazon.com/images/P/0684874350.0...
38,166,High Fidelity,Nick Hornby,1996,Riverhead Books,247,4.056680,http://images.amazon.com/images/P/1573225517.0...
39,172,Good in Bed,Jennifer Weiner,2002,Washington Square Press,490,4.055102,http://images.amazon.com/images/P/0743418174.0...
40,174,Fast Food Nation: The Dark Side of the All-Ame...,Eric Schlosser,2002,Perennial,321,4.037383,http://images.amazon.com/images/P/0060938455.0...
41,175,American Gods,Neil Gaiman,2002,HarperTorch,302,4.006623,http://images.amazon.com/images/P/0380789035.0...
42,176,Skipping Christmas,JOHN GRISHAM,2001,Doubleday,322,4.006211,http://images.amazon.com/images/P/0385505833.0...
43,182,Left Behind: A Novel of the Earth's Last Days ...,Tim Lahaye,1996,Tyndale House Publishers,318,4.003145,http://images.amazon.com/images/P/0842329129.0...
44,184,"The Golden Compass (His Dark Materials, Book 1)",PHILIP PULLMAN,2002,Knopf Books for Young Readers,336,4.000000,http://images.amazon.com/images/P/037582345X.0...
45,192,The Color Purple,Alice Walker,1985,Pocket Books,314,3.964968,http://images.amazon.com/images/P/0671617028.0...
46,198,Silence of the Lambs,Thomas Harris,1991,St. Martin's Press,256,3.960938,http://images.amazon.com/images/P/0312924585.0...
47,201,About a Boy,Nick Hornby,1999,Riverhead Books,262,3.900763,http://images.amazon.com/images/P/1573227331.0...
48,208,Seven Up (A Stephanie Plum Novel),Janet Evanovich,2001,St. Martin's Press,278,3.888489,http://images.amazon.com/images/P/0312265840.0...
49,210,The Alchemist: A Fable About Following Your Dream,Paulo Coelho,1993,HarperSanFrancisco,266,3.875940,http://images.amazon.com/images/P/0062502174.0...